baseURL = "https://spark43.github.io"
languageCode = "en-us"
title = "PhD Dissertation"
theme = 'kaslaanka'

[params]
sitename = "Seoyeong Park - Dissertation"
copyrights = "Seoyeong Park"
defaultList = "global"
paginationLen = 1
#projectsURL = "https://spark43.github.io"
brief_about = "phd dissertation"




[[params.info]]
title = "Persuasion for Prosociality: Understanding Minds for Effective Sociotechnical Systems"
name = "Seoyeong Park"
email = "spark43@ncsu.edu"
date = "2025-11-07"
time = "13:00 - 15:00 EST"
advisor = "Dr. Munindar P. Singh"

[[params.committee]]
name = "Dr. Munindar P. Singh (Chair)"

[[params.committee]]
name = "Dr. David Roberts"

[[params.committee]]
name = "Dr. Sandeep Kuttal"

[[params.committee]]
name = "Dr. Chris Mayhorn"

[[params.abstract]]
content = "abstract"


[[params.defense]]
date = "2025-10-26"
thesisURL = "https://drive.google.com/file/d/17cKxEfsueQ9iYDXyQXM_913mcEgI1t-d/view?usp=sharing"

[[params.doc]]
date = "2024-11-30"
thesisURL = "https://drive.google.com/file/d/1RUE82jG8UdizwnLHkSnxrbOZILcj39hB/view?usp=sharing"

#[[params.myprojects]]
#name = "Totally Awesome Project"
#description = "Machine Learning Magic!!!"
#url = "https://example.com"

#[[params.myprojects]]
#name = "Kaslaanka"
#description = "The best hugo theme ever!!!"
#url = "https://github.com/Iossefy/kaslaanka"

#[[menu.primary]]
#name = "Home"
#url = "/"
#weight = 1

#[[menu.primary]]
#name = "About"
#url = "/about"
#weight = 2

#[[menu.primary]]
#name = "Subscribe"
#url = "/index.xml"
#weight = 3